status: 1
pattern: 'Vacation request from [node:field_employee_sender] to [node:field_employee_sender:entity:field_my_team_lead]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.vacation_request
