_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_roles_gids:
  ceo: 1
  administrator: 2
  team_lead: 3
  dev: 4
  anonymous: 5
  authenticated: 6
  pm: 8
  content_editor: 9
content_access_node_type:
  vacation_request: 'a:3:{s:8:"view_own";a:6:{i:0;s:3:"ceo";i:1;s:9:"team_lead";i:2;s:3:"dev";i:3;s:13:"authenticated";i:4;s:2:"pm";i:5;s:13:"administrator";}s:4:"view";a:3:{i:0;s:3:"ceo";i:1;s:9:"team_lead";i:2;s:13:"administrator";}s:8:"per_node";i:1;}'
  certificate: 'a:2:{s:8:"view_own";a:5:{i:0;s:3:"ceo";i:1;s:9:"team_lead";i:2;s:3:"dev";i:3;s:2:"pm";i:4;s:13:"administrator";}s:4:"view";a:5:{i:0;s:3:"ceo";i:1;s:9:"team_lead";i:2;s:3:"dev";i:3;s:2:"pm";i:4;s:13:"administrator";}}'
