_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  actions_permissions: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  administerusersbyrole: 0
  auto_entitylabel: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bpmn_io: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  condition_field: 0
  conditional_fields: 0
  config: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  ctools_entity_mask: 0
  date_all_day: 0
  date_popup: 0
  datetime: 0
  datetime_extras: 0
  datetime_range: 0
  datetime_range_ef: 0
  dblog: 0
  dynamic_page_cache: 0
  eca: 0
  eca_access: 0
  eca_base: 0
  eca_cache: 0
  eca_config: 0
  eca_content: 0
  eca_endpoint: 0
  eca_form: 0
  eca_log: 0
  eca_migrate: 0
  eca_misc: 0
  eca_modeller_bpmn: 0
  eca_queue: 0
  eca_render: 0
  eca_tamper: 0
  eca_ui: 0
  eca_user: 0
  eca_views: 0
  eca_workflow: 0
  editor: 0
  entity: 0
  entity_reference_exposed_filters: 0
  field: 0
  field_group: 0
  field_token_value: 0
  field_ui: 0
  field_validation: 0
  file: 0
  filter: 0
  group: 0
  help: 0
  history: 0
  hours_minutes_seconds: 0
  image: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_tabs: 0
  jquery_ui_touch_punch: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  masquerade: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_item_role_access: 0
  menu_link_content: 0
  menu_trail_by_path: 0
  menu_ui: 0
  migrate: 0
  modal_page: 0
  mysql: 0
  node: 0
  notifications_widget: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quicktabs: 0
  quicktabs_jqueryui: 0
  rest: 0
  rules: 0
  rules_link_field: 0
  rules_token: 0
  rules_user_fields: 0
  scheduler: 0
  scheduler_rules_integration: 0
  search: 0
  serialization: 0
  shortcut: 0
  smart_date: 0
  smtp: 0
  system: 0
  tab_manager: 0
  tamper: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  variationcache: 0
  vercf: 0
  views_add_button: 0
  views_bulk_operations: 0
  views_cm_current_state: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_ui: 0
  workflow: 0
  workflow_access: 0
  workflow_buttons: 0
  workflows: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bootstrap_barrio: 0
  vacation: 0
profile: standard
