_core:
  default_config_hash: 47YWQALbm33aanLQkeJc91MpPqhtslI3nQG4wCOJrnk
excluded_entities: 'block,block_content_type,block_content,comment_type,contact_form,contact_message,editor,field_storage_config,field_config,field_collection,field_collection_item,file,filter_format,image_style,login_destination,link_configuration_storage,rdf_mapping,rest_resource_config,search_page,shortcut,shortcut_set,action,menu,tour,user_role,menu_link_content,view,entity_form_display,entity_form_mode,entity_view_display,entity_view_mode,date_format,base_field_override'
user_enable: 'Create,Update,Delete'
user_noti_create_message: 'User has been created by [user:name]'
user_noti_update_message: 'User has been updated by [user:name]'
user_noti_delete_message: 'User has been deleted by [user:name]'
user_redirect_create_link: '[entity:url]'
user_redirect_update_link: '[entity:url]'
user_redirect_delete_link: '[entity:url]'
article_enable: 'Create,Update,Delete'
article_noti_create_message: 'Article has been created by [user:name]'
article_noti_update_message: 'Article has been updated by [user:name]'
article_noti_delete_message: 'Article has been deleted by [user:name]'
article_redirect_create_link: '[entity:url]'
article_redirect_update_link: '[entity:url]'
article_redirect_delete_link: '[entity:url]'
certificate_enable: 'Create,Update,Delete'
certificate_noti_create_message: 'Certificate has been created by [user:name]'
certificate_noti_update_message: 'Certificate has been updated by [user:name]'
certificate_noti_delete_message: 'Certificate has been deleted by [user:name]'
certificate_redirect_create_link: '[entity:url]'
certificate_redirect_update_link: '[entity:url]'
certificate_redirect_delete_link: '[entity:url]'
page_enable: 'Create,Update,Delete'
page_noti_create_message: 'Basic page has been created by [user:name]'
page_noti_update_message: 'Basic page has been updated by [user:name]'
page_noti_delete_message: 'Basic page has been deleted by [user:name]'
page_redirect_create_link: '[entity:url]'
page_redirect_update_link: '[entity:url]'
page_redirect_delete_link: '[entity:url]'
vacation_request_enable: 'Create,Update,Delete'
vacation_request_noti_create_message: 'Vacation request has been created by [user:name]'
vacation_request_noti_update_message: 'Vacation request has been updated by [user:name]'
vacation_request_noti_delete_message: 'Vacation request has been deleted by [user:name]'
vacation_request_redirect_create_link: '[entity:url]'
vacation_request_redirect_update_link: '[entity:url]'
vacation_request_redirect_delete_link: '[entity:url]'
comment_enable: 'Create,Update,Delete'
comment_noti_create_message: ' comments has been created by [user:name]'
comment_noti_update_message: ' comments has been updated by [user:name]'
comment_noti_delete_message: ' comments has been deleted by [user:name]'
comment_redirect_create_link: '[entity:url]'
comment_redirect_update_link: '[entity:url]'
comment_redirect_delete_link: '[entity:url]'
position_enable: 'Create,Update,Delete'
position_noti_create_message: 'Position has been created by [user:name]'
position_noti_update_message: 'Position has been updated by [user:name]'
position_noti_delete_message: 'Position has been deleted by [user:name]'
position_redirect_create_link: '[entity:url]'
position_redirect_update_link: '[entity:url]'
position_redirect_delete_link: '[entity:url]'
tags_enable: 'Create,Update,Delete'
tags_noti_create_message: 'Tags has been created by [user:name]'
tags_noti_update_message: 'Tags has been updated by [user:name]'
tags_noti_delete_message: 'Tags has been deleted by [user:name]'
tags_redirect_create_link: '[entity:url]'
tags_redirect_update_link: '[entity:url]'
tags_redirect_delete_link: '[entity:url]'
type_vacation_enable: 'Create,Update,Delete'
type_vacation_noti_create_message: 'Type vacation has been created by [user:name]'
type_vacation_noti_update_message: 'Type vacation has been updated by [user:name]'
type_vacation_noti_delete_message: 'Type vacation has been deleted by [user:name]'
type_vacation_redirect_create_link: '[entity:url]'
type_vacation_redirect_update_link: '[entity:url]'
type_vacation_redirect_delete_link: '[entity:url]'
notfication_widget_conf: 1
