request_state_published:
  workflow_author:
    grant_view: true
    grant_update: true
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
  dev:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
request_state_disapproved:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
  dev:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
request_state_approved:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
  dev:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
state_certificate_publish:
  workflow_author:
    grant_view: true
    grant_update: true
    grant_delete: true
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  anonymous:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  content_editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
state_certificate_disabled:
  workflow_author:
    grant_view: true
    grant_update: true
    grant_delete: true
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  anonymous:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  content_editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
state_for_approvers_disapproved:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  anonymous:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  content_editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
state_for_approvers_assigned:
  workflow_author:
    grant_view: true
    grant_update: true
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: 0
state_for_approvers_approved:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  anonymous:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  content_editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
transaction_type_spent_when_burning_day:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
transaction_type_spent:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
transaction_type_earned:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
request_state_agree:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
request_state_cancel:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
  dev:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
state_for_approvers_cancel:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: 0
    grant_delete: 0
state_for_approvers_started:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: 0
    grant_delete: 0
transaction_type_earned_after_canceled_request:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  ceo:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  team_lead:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  dev:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  pm:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: true
    grant_update: true
    grant_delete: true
